#!/bin/sh

uci set gargoyle.display.firewall_captive_portal='Captive Portal'
uci set gargoyle.scripts.firewall_captive_portal='captive_portal.sh'
uci set gargoyle.firewall.captive_portal='130'
uci commit
